config/routes.rb
Rails.application.routes.draw do

  resources :polls
  root to: 'polls#login'
  get '/users/login/:id' => 'users#login'
  get '/users/error' => 'users#error'
  post '/users/login/:id' => 'users#check_login'
  get '/cancel/:id' => 'users#cancel'
  get '/users/logout/:id' => 'users#logout'

  post '/polls/:id/add_times' => 'polls#add_times'

  get '/polls/:id/invitees' => 'polls#invitees'

  resources :timeslots
  resources :invitees

  post '/polls/:id/publish' => 'polls#publish'
  post '/polls/:id/remind' => 'polls#remind'

  get 'poll_signup/:id' => 'users#poll'
  get 'users/show/:id' => 'users#show'
  post 'poll_signup/:id' => 'users#add_poll'
  get 'signup/:id' => 'users#signup'
  get 'signup_confirmation/:id' => 'users#signup_confirmation'
  get 'thanks' => 'users#thanks'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :admin
  has_many :timeslots, :dependent => :destroy
  has_many :invitees, :dependent => :destroy

  validates :title, presence: true
  validates_length_of :title, minimum: 4

  #validates :location, presence: true

  validates :votes_per_user, presence: true
  validates :votes_per_user, numericality: { greater_than: 0, only_integer: true }
  validates :votes_per_timeslot, presence: true
  validates :votes_per_timeslot, numericality: { greater_than: 0, only_integer: true }
  validates :timezone, presence: true
  validates :timezone, inclusion: { in: %w(EST CST MST PST),
                                    message: '%{value} is not a valid timezone' }

  def add_times

  end

  def self.send_emails(poll_id)
    poll = Poll.find(poll_id)
    invitees = Invitee.where({ poll_id: poll_id })
    invitees.each do |invitee|
      Pony.mail({
                  to: invitee.email,
                  via: :smtp,
                  via_options: {
                    address: 'smtp.gmail.com',
                    port: '587',
                    enable_starttls_auto: true,
                    user_name: 'TheOhmbresSDL3@gmail.com',
                    password: ENV['email_password'],
                    authentication: :login,
                    domain: 'localhost.localdomain'
                  },
                  subject: "Invitation to signup for #{poll.title}",
                  body: "You have been invited to sign-up for a timeslot(s)!
                         Sign-up here: 'https://doodle-hub.herokuapp.com/users/login/#{poll_id}'"
                })
    end
  end

  def self.remind_partial(invitees)
    poll = invitees[0].poll
    invitees.each do |invitee|
      Pony.mail({
                  to: invitee.email,
                  via: :smtp,
                  via_options: {
                    address: 'smtp.gmail.com',
                    port: '587',
                    enable_starttls_auto: true,
                    user_name: 'TheOhmbresSDL3@gmail.com',
                    password: ENV['email_password'],
                    authentication: :login,
                    domain: 'localhost.localdomain'
                  },
                  subject: "Reminder to sign-up for #{poll.title}",
                  body: "You have #{invitee.votes_left} out of #{poll.votes_per_user} votes left in the poll!
                         login and use your remaining votes here: 'https://doodle-hub.herokuapp.com/users/login/#{poll.id}'"
      })
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def poll_params
    params.require(:poll).permit(:title, :description, :location, :votes_per_user, :votes_per_timeslot, :timezone, :deadline)
  end

  def index
    if params[:commit] == 'Login'
      val = authenticate(params[:username], params[:password])
      if ['invalid username', 'invalid password/username'].include?(val)
        redirect_to '/'
        return
      end
    end
    if params[:commit] == 'Publish'
      @poll = Poll.find(params[:publish])
      @poll.published = true
      @poll.save
      Poll.send_emails(params[:publish])
    end
    if params[:commit] == 'Close'
      @poll = Poll.find(params[:close])
      @poll.published = false
      @poll.save
    end
    if params[:commit] == 'Delete'
      poll = Poll.where(id: params[:delete])[0]
      poll&.destroy
    end
    @admin = Admin.find(session[:admin_id])
    @polls = Poll.where({ admin_id: session[:admin_id] })
    if !params[:search_title].nil? && params[:search_title].length.positive?
      @polls = Poll.where({ admin_id: session[:admin_id], title: params[:search_title] })
    end
  end

  def login
    # renders the admin login page no functionality needed
    session[:user_id] = nil
  end

  def authenticate(username, password)
    session[:user_id] = nil
    user_info = Admin.where({ username: username })[0]
    if user_info.nil? || user_info.blank?
      flash[:warning] = 'This username does not exist'
      'invalid username'
    elsif password == user_info.password
      session[:admin_id] = user_info.id
    else
      flash[:warning] = 'Incorrect login credentials'
      'invalid password/username'
    end
  end

  def new
  end

  def create
    poll_info = params[:poll]
    if poll_info["deadline_enable"] == "1"
      deadline = DateTime.new(poll_info['deadline(1i)'].to_i,
                              poll_info['deadline(2i)'].to_i,
                              poll_info['deadline(3i)'].to_i,
                              poll_info['deadline(4i)'].to_i,
                              poll_info['deadline(5i)'].to_i,
                              poll_info['deadline(6i)'].to_i)
    end

    poll = Poll.create({title: poll_info['title'],
                        description: poll_info['description'],
                        location: poll_info['location'],
                        votes_per_user: poll_info['user_votes'],
                        votes_per_timeslot: poll_info['votes_per_timeslot'],
                        timezone: poll_info['timezone'],
                        admin_id: session[:admin_id],
                        deadline: deadline # poll_info['deadline']
                       })

    unless poll.valid?
      flash[:warning] = ''
      poll.errors.keys.each do |key|
        flash[:warning] = flash[:warning] + "#{key} #{ poll.errors[key].first}, "
      end
      flash[:warning] = flash[:warning][0...-2]
      return redirect_to '/polls/new'
    end
    redirect_to "/polls/#{poll.id}/edit?meetings=true"
  end

  def edit
    @timeslots = Timeslot.where(poll_id: params[:id])
    @poll = Poll.find(params[:id])
  end

  def update
    poll_info = params[:poll]

    if poll_info["deadline_enable"] == "1"
      deadline = DateTime.new(poll_info['deadline(1i)'].to_i,
                              poll_info['deadline(2i)'].to_i,
                              poll_info['deadline(3i)'].to_i,
                              poll_info['deadline(4i)'].to_i,
                              poll_info['deadline(5i)'].to_i,
                              poll_info['deadline(6i)'].to_i)
    end


    @poll = Poll.update(params[:poll_id], {title: poll_info['title'],
                                           description: poll_info['description'],
                                           location: poll_info['location'],
                                           votes_per_user: poll_info['votes_per_user'],
                                           votes_per_timeslot: poll_info['votes_per_timeslot'],
                                           timezone: poll_info['timezone'],
                                           deadline: deadline # poll_info['deadline']
    })

    unless @poll.valid?
      flash[:warning] = ''
      @poll.errors.keys.each do |key|
        flash[:warning] = flash[:warning] + "#{key} #{ @poll.errors[key].first}; "
      end
      return redirect_to "/polls/#{@poll.id}/edit?properties=true"
    end
    redirect_to "/polls/#{@poll.id}/edit?meetings=true"
  end

  def invitees
    @poll = Poll.find(params[:id])
    render "/polls/invitees"
  end

  def show
    @show_all = (params[:show_all] == 'false' or params[:show_all].nil?)
    @poll = Poll.find(params[:id])
    @block_data = []
    @poll.timeslots.each do |timeslot|
      timeslot.blocks.each do |block|
        block.invitees.each do |invitee|
          @block_data.append({time: "#{block.timeslot.day.strftime("%m/%d/%Y")} #{block.start} - #{block.end}", invitee: invitee.email})
        end
        if block.invitees.length == 0 and @show_all
          @block_data.append({time: "#{block.timeslot.day.strftime("%m/%d/%Y")} #{block.start} - #{block.end}", invitee: ''})
        end
      end
    end
    @invitee_info = []
    @poll.invitees.each do |invitee|
      @invitee_info.append({votes_left: "#{invitee.votes_left}/#{invitee.poll.votes_per_user}", email: invitee.email, id: invitee.id})
    end
  end

  def remind
    remind_list = []
    Poll.find(params[:id]).invitees.each do |invitee|
      if invitee.votes_left > 0
        remind_list.append(invitee)
      end
    end
    if remind_list.length > 0
      Poll.remind_partial(remind_list)
    end

    render :json => {}
  end

  def publish
    poll = Poll.find(params[:id])
    if poll.timeslots.length == 0
      return render :json => {has_timeslots: false, id: poll.id}
    end
    poll.published = params[:publish] == 'true'
    poll.save
    begin
      if params[:publish] == 'true'
        Poll.send_emails(params[:id])
      end
    rescue ArgumentError => e
      # Ignored
    end
    render :json => {has_timeslots: true, id: poll.id}
  end
end

app/views/polls/index.html.erb
<br>
<br>
<h1><%= @admin.username %>'s Polls</h1>
<br>

<%= form_tag( {controller: polls_path}, {method: "get"}) do %>
  <div style="padding-bottom: 5px;">
    <div class="inline-button-and-text-field"><%= text_field_tag(:search_title, nil, :placeholder => "Poll title") %></div>
    <div class="inline-button-and-text-field"><%= submit_tag("Filter", id:"filter".to_sym) %></div>
  </div>
<% end %>
<br>

<table class="tableFormat">
  <tr>
    <th>Title of Poll</th>
    <th>Description</th>
    <th>Votes Per User</th>
    <th>Votes Per Timeslot</th>
    <th>Timezone</th>
    <th>Location</th>
    <th>Results</th>
    <th>Edit</th>
    <th>Publish</th>
    <th>Delete</th>
  </tr>

  <tbody>
  <% @polls.each do |poll| %>
    <tr>
      <td><%= poll.title %></td>
      <td><%= poll.description %></td>
      <td><%= poll.votes_per_user %></td>
      <td><%= poll.votes_per_timeslot %></td>
      <td><%= poll.timezone %></td>
      <td><%= poll.location %></td>
      <td><%= button_to("Results", "polls/#{poll.id}",:method => :get, id: :poll_results) %></td>
      <td><%= button_to("Edit", "polls/#{poll.id}/edit?meetings=true", :method => :get, class: "edit_poll", id: "edit_poll_#{poll.id}") %></td>
      <td><button class = 'publishButton' id=<%="publish_poll_#{poll.id}"%>><% if poll.published %>Close<% else %>Publish<% end %></button></td>

      <td><%= form_tag( {controller: polls_path, action: :index}, { method: :get }) do %>
          <%= submit_tag("Delete", id: "delete_poll[#{poll.id}]".to_sym,
                         data: { confirm: "Are you sure you want to delete this poll?" }) %>
          <%= hidden_field_tag(:delete,  "#{poll.id}".to_sym) %>
        <% end %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<style>
  @keyframes spinner5 {
    to {
      transform: rotate(360deg);
    }}
</style>
<script type="text/javascript">
  $('.edit_poll').on('click',function(evt) {
    const id = (this.id).split('_')[2];
    evt.preventDefault();
    location.href = '/polls/' + id + '/edit?meetings=true';
  });

  $('.publishButton').click(function(evt) {
    evt.preventDefault();
    const publish = this.textContent === "Publish";
    if(publish){
      const msg = confirm('Are you sure you want to ' + this.textContent + ' this poll? This will email your poll to all invitees');
      if(!msg){
        return
      }
    }
    else{
      const msg = confirm('Are you sure you want to ' + this.textContent + ' this poll?');
      if(!msg){
        return
      }
    }

    const id = this.id.split('_')[2];
    $('#publish_poll_' + id).prop('disabled', true);

    try {
      $.post('polls/' + id +'/publish', {publish: publish},
        function (returnedData) {
          var canPublish = returnedData['has_timeslots'];
          var id = returnedData['id'];
          if(canPublish){
            if(publish){
              document.getElementById('publish_poll_' + id).textContent = "Close";
              alert('the poll has been published');
            }
            else{
              document.getElementById('publish_poll_' + id).textContent = "Publish";
              alert('the poll has been closed');
            }
          }
          else {
            alert('a poll must have at least 1 timeslot before publishing');
          }
          $('#publish_poll_' + id).prop('disabled', false); //.attr("disabled","disabled");
        });
    }
    catch(e) {
      alert(e);
    }
  });
</script>

app/views/polls/invitees.html.erb
<br>
<br>
<h1> Invite People to poll</h1>
<br>
<div style="overflow-y: auto; max-height: 400px; max-width: 350px; box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px; border-radius: 10px;">
  <table style="max-width: 350px;">
    <tr>
      <th>Email</th>
    </tr>
    <% @poll.invitees.each do |invitee| %>
      <tr>
        <td style="float: left"><%= "#{invitee.email}" %></td>
        <td style="float: right; padding-right: 60px;"><%= link_to '', invitee, :method => :delete, :class => 'close'%></td>
      </tr>
    <% end %>
  </table>
</div>

<div style="margin-top: 20px;">
  <div class="inline">
    <button id="add_invitee"> Add </button>
  </div>

  <div class="inline">
    <%= button_to "polls/#{@poll.id}/edit?meetings=true", :method => :get, id: 'back_button' do%>
      Edit Poll
    <% end %>
  </div>

  <div class="inline">
    <%= button_to poll_path, :method => :get, id: 'results_button' do%>
      Results
    <% end %>
  </div>

</div>

<br>

<div>
  <section class="invitee_form" style="display: none;">
    <%= form_tag( "/invitees", :method => :post, :id => 'add_invitee') do %>
      <%= label(:email_label, "Email") %>
      <div style="padding-bottom: 10px"><%= text_field :invitee, :email %></div>
      <%= hidden_field_tag 'poll', @poll.id %>
      <div style="float: left"><%= submit_tag "Add" %></div>


    <% end %>

      <div style="float: left"><button id="cancel_add"> cancel </button></div>


  </section>
</div>

<script type="text/javascript">
  $('#add_invitee').on('click',function(evt) {
    $('.invitee_form').show();
  });
  $('#cancel_add').on('click',function(evt) {
    $('.invitee_form').hide();
  });
  $('#back_button').on('click',function(evt) {
    evt.preventDefault();
    location.href = 'edit?meetings=true';
  });
</script>

app/views/polls/login.html.erb
<style>
  body,
  html {
    margin: 0;
    height: 100%;
  }
</style>

<!--https://codepen.io/Tbgse/pen/JXrJGX-->
<div class='bold-line'></div>
<div class='container'>
  <div class='window'>
    <div class='overlay'></div>
    <div class='content'>
      <div class='welcome'>Sign In</div>
      <div class='input-fields'>
        <%= form_tag( {controller: polls_path}, {method: :get}) do %>
          <br>
          <%= text_field_tag(:username, nil, :placeholder => "Username", :class => "input-line full-width" ) %>
          <br>
          <br>

          <%= password_field_tag(:password, nil, :placeholder => "Password", :class => "input-line full-width") %>
          <br>
          <br>
          <br>
          <div style="text-align: center; font-size: large">
            <% if flash[:notice]%>
              <div class="notice" style="margin-bottom: 10px; margin-top: 0px; background-color:rgba(0,0,0,0); color: #3e9941;">
                <%= flash[:notice]%>
              </div>
            <% elsif flash[:warning]%>
              <div class="warning" style="margin-bottom: 10px; margin-top: 0px; background-color:rgba(0,0,0,0); color: #d53131;">
                <%= flash[:warning]%>
              </div>
            <% end %>
          </div>
          <%= submit_tag("Login", id: :login, class: 'ghost-round full-width', style: "background: transparent") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/polls/new.html.erb
<%#= render :layout => "layouts/popup" , :locals => {:title => 'some title'} do%>
<div id="new_poll_page_id">
  <% provide(:title, "Create Poll") %>
  <br>
  <br>
  <h1>Create Poll</h1>
  <div>
    <%= form_tag( "/polls", :method => :post, :id => 'add_new_poll') do %>
      <%= label(:title_label, "Title") %>
      <%= text_field(:poll, :title, :placeholder => "Enter poll name here", required: true) %>

      <%= label_tag(:location_label, "Location") %>
      <%= text_field(:poll, :location, :placeholder => "e.g. SC 3258") %>

      <%= label_tag(:description_label, "Description") %>
      <%= text_area(:poll, :description, :placeholder => "The poll description...", :style => "width: 200px; resize: none; height: 65px; text-align: left;" ) %>

      <%= label_tag(:user_votes_label, "Votes per User") %>
      <%= text_field(:poll, :user_votes, required: true, value: 1) %>

      <%= label_tag(:votes_per_timeslot_label, "Votes per Timeslot") %>
      <%= text_field(:poll, :votes_per_timeslot, required: true, value: 1) %>

      <%= label_tag(:timezone_label, "Timezone", required: true) %>
      <br>
      <%= select(:poll, :timezone, [ ['Eastern (UTC-05:00)', "EST"],
                                     ['Central (UTC-06:00)', "CST"],
                                     ['Mountain (UTC-07:00)', "MST"],
                                     ['Pacific (UTC-08:00)', "PST"]], { include_blank: true }) %>
      <br>

      <%= label_tag(:votes_per_timeslot_label, "Deadline (optional)") %>
      <%= check_box :poll, :deadline_enable, :checked => "unchecked", :onclick => "$('#deadline_display').toggle()" %>
      <div id="deadline_display" style="display: none">
        <%= datetime_select(:poll, :deadline, id: :deadline, ) %>
      </div>


      <br>
      <%= submit_tag("Create!",  name: "create_poll_button", id: "create_poll_button") %>
    <% end %>
  </div>
</div>

<%# end %>

app/views/polls/show.html.erb
<br>
<br>
<h1>Results</h1>
<br>

<div class="row">
  <div class="columnLeft">
    <div style="overflow-y: auto; max-height: 300px; border-radius: 10px; max-width: 550px; box-shadow: rgba(98, 98, 98, 0.23) 0px 3px 6px;">
      <table>
        <tr>
          <th>Date</th>
          <th>User</th>
        </tr>
        <% @block_data.each do |block| %>
          <tr>
            <td><%= block[:time] %></td>
            <td><%= block[:invitee] %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <br>
    <div>
      <div class="inline">
        <%= button_to "#{@poll.id}/invitees", :method => :get, id: 'invite_button' do%>
          Invite
        <% end %>
      </div>

      <div class="inline">

        <button id = 'remindButton'  <%= if @poll.published then "" else "disabled" end%>>Remind</button>
      </div>

      <div class="inline">
        <%= button_to poll_path, method: :get, params: { show_all: @show_all}, id:'reserved_button' do%>
          <% if @show_all  %>
            Show Only Reserved
          <% else %>
            Show All
          <% end %>
        <% end %>
      </div>

      <div class="inline">
        <Button id = 'publish'><% if @poll.published %>Close<% else %>Publish<% end %></Button>
      </div>

    </div>
  </div>

  <div class="columnRight">
    <div style="overflow-y: auto; max-height: 400px; border-radius: 10px; max-width: 550px; box-shadow: rgba(98, 98, 98, 0.23) 0px 3px 6px;">
      <table>
        <tr>
          <th>Email</th>
          <th>Votes Left</th>
        </tr>
        <% @invitee_info.each do |invitee| %>
          <tr>
            <td style="width: 200px"><%= invitee[:email] %></td>
            <td><%= invitee[:votes_left] %></td>
            <td><%= link_to '', Invitee.find(invitee[:id]), :method => :delete, :class => 'close'%></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

</div>







<script type="text/javascript">
  $('#remindButton').click(function(evt) {
    $('#remindButton').prop('disabled', true);
    $("#loading_bar").show()
    try {
      $.post("/polls/" + <%=@poll.id.to_s %> +'/remind', {id: <%=@poll.id%>},
        function (returnedData) {
          canPublish = returnedData['has_timeslots'];
          alert('an alert has been sent out to all remaining voters');
          $('#remindButton').prop('disabled', false); //.attr("disabled","disabled");
          $("#loading_bar").hide()
        });
    }
    catch(e) {
      alert(e);
    }
  });
  $('#publish').click(function(evt) {
    $("#loading_bar").show()
    const publish = this.textContent === "Publish";
    $('#publish').prop('disabled', true);
    try {
      $.post(<%=@poll.id.to_s %> +'/publish', {publish: publish},
        function (returnedData) {
          var canPublish = returnedData['has_timeslots'];
          var id = returnedData['id'];
          if(canPublish){
            if(publish){
              $('#publish').html( "Close" );
              alert('the poll has been published');
            }
            else{
              $('#publish').html("Publish");
              alert('the poll has been closed');
            }
          }
          else {
            alert('a poll must have at least 1 timeslot before publishing');
          }
          $('#publish').prop('disabled', false); //.attr("disabled","disabled");
          $("#loading_bar").hide()
        });
    }
    catch(e) {
      alert(e);
    }
  });
</script>